# Global configuration
safe: True
exclude: ["README.md"]
timezone: "Europe/Paris"

# Serve command options
url: "http://naveau.github.io"
baseurl: ""

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"
      lang: "en"
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Mikaël Naveau"
      permalink: /:day-:month-:year/:title
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"      

# sass
sass:
  sass_dir: assets/stylesheets


